default:
  toolbar:
    - undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
  plugins:
    - image
    - link
